### ISSUE TITLE
DEBUG under MSVC++ works,  yet installed in OpenCPN v4.6 Instant Crash

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/celestial_navigation_pi#16]
After compiling debug version and copying it all over to MSVC++ where I could make multiple fixes!

No dependencies. put opencpn.lib v4.2 in build directory.

I have deleted and cloned and compiled again (completed properly), then installed in Opencpn v4.6.
(I am using v4.2 Opencpn.lib) 

Checked all the installation, the dll location, and cel_nav_pi/data/ etc.

As soon as I touch or click on the Cel_Nav Icon all of OpenCPN instantly disappears!

Very puzzled.

Below is when adding many fixes to Cel_Nav in MSVC++ DEBUG MODE  (No problems)
![celestial-nav-debug-msvc](https://cloud.githubusercontent.com/assets/2363959/24673378/1dc989ba-1946-11e7-9d92-77427b161725.png)

**Comment by rgleason** [comment]
I just tested this again, after git fetch and compile on my laptop. 
1. Release version compiles with No Errors, installs, but Opencpn crashes instantly when it is enabled.
2. Debug version in MS Visual Studio seems to work fine!

Therefore I cannnot give you any information about the bug!!

**Comment by rgleason** [comment]
This is old, and no longer what happens.

**Comment by stelian42** [comment]
This can be closed now, is fixed in main tree.

**Comment by rgleason** [comment]
I would not call them Miscellaneous!! I'll  close when your PR is Merged.
