### ISSUE TITLE
Inaccuracies in the Mac 2.0 version reported by David from Starpath: We need to compile Cel_Nav 2.3 for MAC

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/celestial_navigation_pi#29]
Please see his correspondence, so we can get this resolved. Dave R and David from Starpath have sent emails.

**Comment by rgleason** [comment]
I tried to compile the last version but when loaded and executed in Opencpn V4.8.6, Opencpn fails, which indicates that that version of the plugin is not compatible with wxwidgets 3.0.2.  It appears that the "doc update" commit  e5cf65081de31544a3c27b6c4a909d96ca3e10b8   was working before wxwidgets 3.0.2 upgrade.

In short, the best way forward is to get the star data and associated changed in the current plugin without changing all the other improvements.

Of course, the other alternative is to use that compile with the earlier version of O, not very useful.

**Comment by rgleason** [comment]
Commit  "Doc update"  Commit e5cf65081de31544a3c27b6c4a909d96ca3e10b8  
https://github.com/rgleason/celestial_navigation_pi/commit/e5cf65081de31544a3c27b6c4a909d96ca3e10b8

Is the most recent Star Table Lookup data that works.

**Comment by starpathnav** [comment]
With my apologies. i had mixed up the pc version numbers. It seems to me now that it is only the Mac ver 2.0 that has the star data off. see attached file.
[opencpn data.pdf](https://github.com/seandepagnier/celestial_navigation_pi/files/2545298/opencpn.data.pdf)

**Comment by rgleason** [comment]
Clarification: 

- Windows Celestial_Navigation_pi 2.3 is OK.
- Mac Celestial_Navigation_pi 2.0 needs to be updated to version 2.3 which incorporates Povl Abrahamsen's corrections and improvements.

**Comment by rgleason** [comment]
Peter T. has compiled v2.3 for Mac. David B. is testing. Will send link to Povl.
Then once tested we will add to downlaods on the website.

**Comment by rgleason** [comment]
This has been tested and it works. Closing
