### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [seandepagnier/celestial_navigation_pi#3]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by dominig** [comment]
I am doing the packaging work for OpenSUSE and I have the same issue.
Tag would be nice.
Thanks
Dominig

**Comment by mschiff** [comment]
Ping?

**Comment by dominig** [comment]
Yes,
I am here. Can be contacted directly by mail.
dominig dot arfoll at fridu dot net

**Comment by rgleason** [comment]
Dominig & mshiff, he may be on a voyage. Eventually Sean will respond.

**Comment by rgleason** [comment]
@mschiff  We are tagging now. Please close this.

**Comment by mschiff** [comment]
Thanks!
