### ISSUE TITLE
Main window not visible on OSX

### ISSUE THREAD

**Issue by adwuk** [seandepagnier/celestial_navigation_pi#7]
When opening the main plugin window on OSX, it is hardly visible.  I have commented out the line 113 of CelestialNavigationDialog.cpp which sorts the problem.

`113:  //SetTransparent(128);`

**Comment by stelian42** [comment]
I vote for this too. On Linux too the window is difficult to see.

**Comment by stelian42** [comment]
This can be closed now, is fixed in main tree.

**Comment by rgleason** [comment]
Sean or Adwuk have to close this.

**Comment by rgleason** [comment]
This should be closed by now.  Sean or Adwuk, please close!

**Comment by rgleason** [comment]
Can be closed by Sean now.

**Comment by rgleason** [comment]
@adwuk Please close this is fixed.
